### ISSUE TITLE
Some parameters description missing in the readthedocs

### ISSUE THREAD

**Issue by couasnonanais** [Leynse/SFINCS#3]
I was looking at the description of some parameters/options (hutresh and min_level_hmax) and couldn't find the descriptions on the readthedocs. However I see some description of huthresh (and other parameters) in SFINCS>docs>parameters.rst that do no appear on the webpage. I couldn't find any description for min_level_hmax. This would be useful to add for users. Thanks!

**Comment by Leynse** [comment]
Thanks for noticing!
Due to an error huthresh was not visible in de parameters.rst, now will be fixed in new version.
In recent version of SFINCS, 'min_level_hmax' is not used anymore so therefore not included
